spring:
  application:
    name: gateway-server

server:
  port: 8899

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hello-service

eureka:
  instance:
#    hostname: localhost
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka
