server:
  port: 2233
spring:
  application:
    name: hello-service

info:
 app:
  name: spring-boot-hello
  version: v1.0.0
  #服务跟踪
#  zipkin:
#    enabled: true
#    base-url: http://10.16.8.97:9411
#  sleuth:
#    sampler:
#      percentage: 1.0
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
            defaultZone: http://127.0.0.1:1111/eureka/
#            defaultZone: http://10.236.128.226:1111/eureka/
endpoints:
  shutdown:
    enabled: true
    sensitive: false
  restart:
    enabled: true
    sensitive: false
  trace:
    enabled: true
    sensitive: false
  dump:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
  logfile:
    enabled: true
    sensitive: false
  configprops:
    enabled: true
    sensitive: false

security:
  basic:
    enabled: false
management:
  security:
    enabled: false









