spring:
  application:
    name: saasp-configctr

server:
  port: 1111

eureka:
  instance:
    prefer-ip-address: true
    hostname: peer2
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
  client:
    serviceUrl:
      defaultZone: http://10.16.8.96:1111/eureka/

endpoints:
  shutdown:
    enabled: true



